[WIP] TPC: Added expert visulization task for creating ND monitoring data
AliceO2Group/QualityControl pull request #1095
Opened 2022-03-15 11:56 UTC by bulukutlu

Created a new task that generates THnSparse files to be used in the TPC by the detector experts

2022-03-15 11:59 UTC, bulukutlu commented
This depends on https://github.com/AliceO2Group/AliceO2/pull/8354

2022-03-16 09:13 UTC, wiechula requested changes

2022-03-16 09:13 UTC, wiechula commented on Modules/TPC/include/TPC/ExpertVis.h
> +  ExpertVis();
```suggestion
  ExpertVis() = default;
```

2022-03-16 09:13 UTC, wiechula commented on Modules/TPC/src/ExpertVis.cxx
> +}
```suggestion
```

2022-03-16 09:13 UTC, wiechula commented on Modules/TPC/src/ExpertVis.cxx
> +  getObjectsManager()->startPublishing(&mQCExpertVis.getHistogramTracks());
```suggestion
  getObjectsManager()->startPublishing(mQCExpertVis.getHistogramPID());
  getObjectsManager()->startPublishing(mQCExpertVis.getHistogramTracks());
```
After changes in O2

2022-03-16 13:02 UTC, wiechula approved these changes

2022-03-16 19:25 UTC, stheckel commented
As just discussed on the corresponding O2 PR, further tests and potentially reconsideration is needed, so please also mark this one here again as draft, so the CI does not continuously try to rebuild.

2022-08-09 05:43 UTC, Barthelemy commented
Hello, 
This PR has been in progress for quite some time. Would you mind if we closed it and you reopen when it is ready ? 
Cheers,
Barth

2022-08-09 05:50 UTC, bulukutlu commented
Further tests needed investigating memory and space requirements, will open again when ready.

2022-08-09 05:50 UTC, closed without merging