TRD redo connection to ccdb
AliceO2Group/QualityControl pull request #1156
Opened 2022-04-26 11:36 UTC by bazinski

This fixes the crashes seen online.

It removes double deletion locally, so should be good for online.

2022-04-26 12:02 UTC, bazinski commented
@tdietel @martenole  could you guys approve this soonish?
Apparently qc will get tagged tomorrow.

2022-04-26 12:10 UTC, martenole commented
Sorry I am afraid I don't really understand the changes. But I am also no codeowner of the TRD code in QC, so my approval does not really matter.
I thought the double deletion occurred at the EOR only. Don't the changes here only affect the initialization phase?

2022-04-26 12:14 UTC, bazinski commented
@martenole I thought so as well, but as soon as I commented the ccdb connection out the problem went away.
one gets a double deletion error and then it takes ages to end. 
Was testing on a single time frame, and the workflow (raw-tf | datareader | qc | o2-dpl-run) would just hang for ages, never waited for it to finish but would come back with an error number after killing. 

This now uses qc's connection to ccdb, not a manual one.
I know you and also @tdietel are not code owners, but figured @Barthelemy and or @knopers8  would query trd so in the interests of getting this through quickly, I figured I would preempt that ;-)

2022-04-26 12:34 UTC, martenole commented
Hm ok. When using the CCDB manager I think one should anyhow always use raw pointers. Probably exactly to avoid these problems :)
If the QC's connection works differently then probably this is ok. Otherwise I would just use (const) pointers instead of shared_ptr.

2022-04-26 12:45 UTC, tdietel approved these changes
Looks like this is a good shot at fixing the double free bug we have in the TRD QC at the moment. I suggest to merge this before the next tag. Good work, Sean.

2022-04-27 06:51 UTC, Barthelemy requested changes

2022-04-27 06:51 UTC, Barthelemy commented on Modules/TRD/include/TRD/TrackletsTask.h
> +  o2::quality_control::repository::DatabaseInterface* mDatabase = nullptr;
why do you need this variable ?

2022-04-27 06:51 UTC, Barthelemy commented on Modules/TRD/src/PulseHeight.cxx
> +  //mNoiseMap.reset(ccdbmgr.get<o2::trd::NoiseStatusMCM>("/TRD/Calib/NoiseMapMCM"));
The coding guidelines recommend removing the code instead of commenting it out.

2022-04-27 06:51 UTC, Barthelemy commented on Modules/TRD/src/PulseHeight.cxx
> +  mNoiseMap.reset((o2::trd::NoiseStatusMCM*)retrieveCondition("/TRD/Calib/NoiseMapMCM"));
We forbid c-style casts in O2. Please use `reinterpret_cast`, `static_cast` or `dynamic_cast` depending on the case.

2022-04-27 06:51 UTC, Barthelemy commented on Modules/TRD/src/TrackletsTask.cxx
> +void TrackletsTask::retrieveCCDBSettings()
This is a duplicate. Please move it to a header accessible by both classes.

2022-04-27 10:05 UTC, bazinski commented
The macOS errors are missing libraries and some stuff not related to this code.

2022-04-27 10:09 UTC, Barthelemy commented
yes, this is a problem with the builder.

2022-04-27 10:09 UTC, Barthelemy approved these changes

2022-04-27 10:10 UTC, merged