ZDC Implement checker for task-raw and task-rec. Add New histograms
AliceO2Group/QualityControl pull request #1540
Opened 2022-10-26 15:18 UTC by cpuggion84

Implement ZDCRawDataCheck and ZDCRecDataCheck
ZDCRawDataTask: 
- Add rate histogram
- add bin histogram parameters
ZDCRecDataTask: 
- Add histograms: summary_adc, summary_TDC 
- Minor changes

2022-10-26 15:26 UTC, cpuggion84 commented
It will be necessary to modify the json file on consule at p2.

If it is not changed. The tasks will work, but can't run the checker. The raw task will be get the bin of histograms by default write in the code and not from json file.

2022-11-01 15:08 UTC, knopers8 requested changes
Hi @cpuggion84 , thank you for the PR, could you please address these comments before we merge it?

2022-11-01 15:08 UTC, knopers8 commented on Modules/ZDC/etc/zdcTaskRawData.json
> +        "url": "http://consul-test.cern.ch:8500"
Please keep it empty, this host is not available anymore anyway.

2022-11-01 15:08 UTC, knopers8 commented on Modules/ZDC/include/ZDC/ZDCRecDataCheck.h
> +/// \author My Name
Please add your name

2022-11-01 15:08 UTC, knopers8 commented on Modules/ZDC/include/ZDC/ZDCRecDataCheck.h
> +/// \author My Name
Please update the doc here

2022-11-01 15:08 UTC, knopers8 commented on Modules/ZDC/src/ZDCRawDataCheck.cxx
> +        result.addReason(FlagReasonFactory::Unknown(), "It is Good");
If it is good, there is no need to add a `FlagReason` which indicates that the quality is bad. I would remove it.

2022-11-01 15:08 UTC, knopers8 commented on Modules/ZDC/src/ZDCRawDataCheck.cxx
> +  dumpFile.open("dumpStructuresRawCheck.txt");
I see this is commented out, but please do not assume in general that you will be able to open a file, could you add a check before you write to it?

2022-11-01 15:08 UTC, knopers8 commented on Modules/ZDC/src/ZDCRecDataCheck.cxx
> +        result.addReason(FlagReasonFactory::Unknown(), "ZDCRecDataTask quality is Good");
as said before, I would remove it, since the flag "Unknown" is to mark data as bad, but you cannot say why it is bad.

2022-11-01 15:08 UTC, knopers8 commented on Modules/ZDC/src/ZDCRecDataCheck.cxx
> +                           "It is medium because in TDC Summary " + std::to_string(mNumWTDC) + " channels:" + mStringWTDC + "have a value in the medium range");
here you are saying it is medium, but you are setting the quality::bad, is that a typo?

2022-11-01 15:08 UTC, knopers8 commented on Modules/ZDC/src/ZDCRecDataCheck.cxx
> +  dumpFile.open("dumpStructuresRecCheck.txt");
the same as before

2022-11-04 11:28 UTC, cpuggion84 commented
> Hi @cpuggion84 , thank you for the PR, could you please address these comments before we merge it?

I have updated the code with the required changes. Thanks for the corrections

2022-11-07 15:56 UTC, cpuggion84 commented
I changed the control of the file.
I use that file only in the debug phase when I develop the software. I need to check if the data structures I use are filled correctly. In fact, I always comment the writing when I commit the code. I would need this code to be running at P2 for pb-pb low intensity tests

2022-11-10 07:36 UTC, knopers8 commented on Modules/ZDC/include/ZDC/ZDCRecDataCheck.h
> +/// \author alienv enter Readout/latest
typo here

2022-11-10 07:36 UTC, knopers8 approved these changes

2022-11-10 07:36 UTC, merged