Add new CalibMQcTask
AliceO2Group/QualityControl pull request #1633
Opened 2023-02-03 16:46 UTC by ValerieRamillien

2023-02-06 07:43 UTC, Barthelemy requested changes

2023-02-06 07:43 UTC, Barthelemy commented on Modules/MUON/MID/include/MID/CalibMQcCheck.h
> +  float nTF = 0;
The naming scheme specifies that the members should start with an `m`.  
https://rawgit.com/AliceO2Group/CodingGuidelines/master/naming_formatting.html#Variable_Names

2023-02-06 07:43 UTC, Barthelemy commented on Modules/MUON/MID/include/MID/CalibMQcTask.h
> +  int nTF = 0;
same here

2023-02-06 07:43 UTC, Barthelemy commented on Modules/MUON/MID/src/CalibMQcTask.cxx
> +  ILOG(Info, Support) << "initialize CalibMQcTask" << ENDM; // QcInfoLogger is used. FairMQ logs will go to there as well.
Perhaps you could use `ILOG(Debug, Devel)` instead.

2023-02-06 07:43 UTC, Barthelemy commented on Modules/MUON/MID/src/CalibMQcTask.cxx
> +  ILOG(Info, Support) << "initialize CalibMQcTask" << ENDM; // QcInfoLogger is used. FairMQ logs will go to there as well.
Also for the others further down the code.

2023-02-06 07:43 UTC, Barthelemy commented on Modules/MUON/MID/src/CalibQcTask.cxx
> +  std::cout << "!!!! START initialize CalibQcTask !!!! " << std::endl;
Please use `ILOG` instead of `cout`.

2023-02-06 07:43 UTC, Barthelemy commented on Modules/MUON/MID/src/CalibQcTask.cxx
> +  std::cout << "!!!! START monitorData CalibQcTask !!!! " << std::endl;
logging and printing should not happen in `monitorData` (apart for the development). It results in a very large amount of logs.

2023-02-06 07:44 UTC, Barthelemy commented
Good, thank you, just a few changes to be made (and one conflict apparently due to another PR).

2023-02-06 09:59 UTC, ValerieRamillien commented
Hello Barthelemy,
Ok I will change it. Thank you.
Valerie.

> Le 6 févr. 2023 à 08:44, Barthélémy von Haller ***@***.***> a écrit :
> 
> 
> Good, thank you, just a few changes to be made (and one conflict apparently due to another PR).
> 
> —
> Reply to this email directly, view it on GitHub <https://github.com/AliceO2Group/QualityControl/pull/1633#issuecomment-1418643965>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/AW2SC7ZXWFWBCFQTYJULZDLWWCTUXANCNFSM6AAAAAAUQO7MTQ>.
> You are receiving this because you authored the thread.
>

2023-02-10 07:37 UTC, Barthelemy approved these changes

2023-02-10 07:37 UTC, merged