[WIP] TPC: Update CheckOfTrendings
AliceO2Group/QualityControl pull request #1649
Opened 2023-02-24 09:15 UTC by mlesch

Changes: new checks (range check and zero check), new visualization (e.g. running mean) and inclusion of uncertainties of data points in the calculation of mean

2023-03-02 12:10 UTC, wiechula requested changes
Please carefully check the naming convention of functions and variables.

2023-03-02 12:10 UTC, wiechula commented on Modules/TPC/src/CheckOfTrendings.cxx
> +  ;
```suggestion
```

2023-03-02 12:10 UTC, wiechula commented on Modules/TPC/src/CheckOfTrendings.cxx
> +    ILOG(Error, Support) << "NO ERRORS" << ENDM;
I guess this can be warning or info

2023-03-02 12:10 UTC, wiechula commented on Modules/TPC/src/CheckOfTrendings.cxx
> +    bool AllZeros = std::all_of(v.begin(), v.end(), [](double i) { return std::abs(i) == 0.0; });
```suggestion
    const bool AllZeros = std::all_of(v.begin(), v.end(), [](double i) { return std::abs(i) == 0.0; });
```

2023-03-02 12:10 UTC, wiechula commented on Modules/TPC/src/CheckOfTrendings.cxx
> +    int Worst_Quality_Index = std::distance(qualities.begin(), Worst_Quality);
this variable is not used

2023-03-02 12:10 UTC, wiechula commented on Modules/TPC/src/CheckOfTrendings.cxx
> +  auto* canv = dynamic_cast<TCanvas*>(mo->getObject());
`nullptr` check needed?

2023-03-02 12:10 UTC, wiechula commented on Modules/TPC/src/CheckOfTrendings.cxx
> +    bool UseErrors = true;
Naming convention!

2023-03-03 09:34 UTC, mlesch commented
@wiechula thanks for the review! I implemented all requested changes

2023-03-06 11:47 UTC, wiechula requested changes

2023-03-06 11:47 UTC, wiechula commented on Modules/TPC/include/TPC/CheckOfTrendings.h
> +#include <TCanvas.h>
Forward declare:

```suggestion
class TGraph;
class TCanvas;
```

And move
```
#include <TGraph.h>
#include <TCanvas.h>
```
to the `cxx`

2023-03-08 08:53 UTC, mlesch commented
@wiechula Thanks, I changed it to forward declaration

2023-03-08 21:25 UTC, wiechula approved these changes
Looks fine I think. Do you want to remove the WIP?

2023-03-09 20:01 UTC, merged