TPC: Update TPC Trending
AliceO2Group/QualityControl pull request #1655
Opened 2023-03-01 09:35 UTC by mlesch

Changes: 

- Add possibility to trend vs run-number 
- Add possibility to add a new histogram as datasource for a continues trend

2023-03-01 10:21 UTC, wiechula requested changes
Just minor comments

2023-03-01 10:21 UTC, wiechula commented on Modules/TPC/src/TrendingTaskTPC.cxx
> +      bool existingBranch = mTrend->GetBranchStatus(source.name.c_str());
```suggestion
      const bool existingBranch = mTrend->GetBranchStatus(source.name.c_str());
```

2023-03-01 10:21 UTC, wiechula commented on Modules/TPC/src/TrendingTaskTPC.cxx
> +        ;
There is an empty line with `;`. And perhaps for better readability `timeStamp` -> `xVal`
```suggestion
        const double xVal = (trendType == "time") ? (double)(*retrieveTime) : (double)(*retrieveRun);

```

2023-03-01 10:21 UTC, wiechula commented on Modules/TPC/src/TrendingTaskTPC.cxx
> +        ;
See above
```suggestion
        const double xVal = (trendType == "multigraphtime") ? (double)(*retrieveTime) : (double)(*retrieveRun);
        
```

2023-03-01 10:21 UTC, wiechula commented on Modules/TPC/src/TrendingTaskTPC.cxx
> +    const double timeStamp = (trendType == "time") ? (double)(*retrieveTime) : (double)(*retrieveRun);
See above
```suggestion
    const double xVal = (trendType == "time") ? (double)(*retrieveTime) : (double)(*retrieveRun);
```

2023-03-01 11:27 UTC, mlesch commented
Thanks! I implemented all comments as suggested

2023-03-02 12:14 UTC, wiechula approved these changes

2023-03-02 12:14 UTC, merged