[EMCAL-767]: Add histograms for # of good, bad, dead cells in EMCAL/DCAL.
AliceO2Group/QualityControl pull request #1714
Opened 2023-04-06 14:37 UTC by hjbossi

2023-04-06 14:37 UTC, hjbossi commented
@mfasDa @jokonig to check

2023-04-10 19:08 UTC, mfasDa requested changes
Few things to be changed. In particular I think it is computing wise more advantageous to use a separate loop over the channels for filling the stat histograms, because they are potentially expensive.

2023-04-10 19:08 UTC, mfasDa commented on Modules/EMCAL/src/CalibMonitoringTask.cxx
> +      mBadChannelMapEMCALHisto = new TH2D("badChannelMapEMCAL", "Number of Good/Dead/Bad Channels in EMCAL Only", 3, 0, 2, 12288, 0, 12288);
Maybe use a more specific histogram name, like maskStatsEMCAL/DCAL.

2023-04-10 19:08 UTC, mfasDa commented on Modules/EMCAL/src/CalibMonitoringTask.cxx
> +      mBadChannelMapDCALHisto = new TH2D("badChannelMapDCAL", "Number of Good/Dead/Bad Channels in DCAL Only", 3, 0, 2, 5376, 0, 5376);
Same as above.

2023-04-10 19:08 UTC, mfasDa commented on Modules/EMCAL/src/CalibMonitoringTask.cxx
> +          }
There is also a pointer to the bad channel map itself, you would not need the geometry functions, you know the tower ID. Iterating over the bad channel map is super fast, calculating the the cell indices is potentially expensive, a separate for loop makes sense for performance reasons.

2023-04-20 06:37 UTC, knopers8 approved these changes

2023-04-21 08:32 UTC, mfasDa commented
CI errors now unrelated

2023-04-21 11:24 UTC, merged