[QC-974] Introduce mergeable histogram ratios
AliceO2Group/QualityControl pull request #1784
Opened 2023-05-21 13:32 UTC by aferrero2707

This PT introduces two generic classes that allow to create and publish histogram ratios in QC tasks.
The classes derive from MergeInterface, such that histogram rations from multiple sources can be properly combined on the merger nodes.
One class introduces ratios of TH1D histograms, and the other of TH2F histograms.

The classes can be conveniently used to normalize plots to the number of processed TFs or orbits, or to compute efficiencies.

The `uniformScaling` constructor parameter controls whether the denominator is a single constant (practically implemented as a 1-bin histogram) or if each bin has its own denominator value (in which case the numerator and denominator histograms have the same number of bins).
The first option allows to save memory and is appropriate for global histogram normalization, while the second is more flexible and appropriate for efficiency-like histograms.

2023-05-21 13:36 UTC, aferrero2707 commented
@knopers8 @Barthelemy this is a draft implementation of some generic histogram normalization/ratio classes we discussed with Piotr. I still have to write some documentation. Could you please have a look and let me know if the codeis ok for you?

The code is partly inspired from ROOT's [TEfficiency class](https://root.cern/root/html606/TEfficiency_8cxx_source.html).

2023-05-22 09:13 UTC, knopers8 requested changes
Thank you! The code looks reasonable, I have only "editorial" comments.

Since this class seems easy to test, would you consider adding a test in `Common/test`?

2023-05-22 09:13 UTC, knopers8 commented on Modules/Common/include/Common/TH1Ratio.h
> +#include <iostream>
```suggestion
```
These two do not seem to be needed in the header.

2023-05-22 09:13 UTC, knopers8 commented on Modules/Common/include/Common/TH1Ratio.h
> +#include <TList.h>
This one neither
```suggestion
```

2023-05-22 09:13 UTC, knopers8 commented on Modules/Common/include/Common/TH1Ratio.h
> +using namespace std;
```suggestion
```

2023-05-22 09:13 UTC, knopers8 commented on Modules/Common/src/TH1Ratio.cxx
> +}
I assume this comes from the ROOT's class. As far as I understand, we do not need these placeholder methods in our case, so perhaps you could remove them?

2023-05-22 09:13 UTC, knopers8 commented on Modules/Common/src/TH2Ratio.cxx
> +}
```suggestion

void TH2Ratio::SetBins(Int_t nx, Double_t xmin, Double_t xmax,
                       Int_t ny, Double_t ymin, Double_t ymax)
{
  getNum()->SetBins(nx, xmin, xmax, ny, ymin, ymax);
  getDen()->SetBins(nx, xmin, xmax, ny, ymin, ymax);
  TH2F::SetBins(nx, xmin, xmax, ny, ymin, ymax);
}
```

same here (and header files)

2023-05-22 09:13 UTC, knopers8 commented on Modules/Common/src/TH2Ratio.cxx
> +#include <limits>
```suggestion
```
I don't see them used, could you please remove them to reduce the compilation time?

2023-05-22 09:13 UTC, knopers8 commented on Modules/Common/src/TH1Ratio.cxx
> +using namespace std;
```suggestion
```
Probably not needed.

2023-05-22 17:10 UTC, aferrero2707 commented on Modules/Common/include/Common/TH1Ratio.h
> +class TH1Ratio : public TH1D, public o2::mergers::MergeInterface
I was also thinking about using a template, but was not sure you would like the idea. Since we seem to agree on that, I will give it a try.

2023-05-24 22:59 UTC, aferrero2707 commented
@knopers8 I re-implemented the two classes as templates, and added some unit tests. For the templates, I have decided to put the method implementation into a separate file with respect to the class declarations, for better readability. Let me know if that's ok for you.

2023-05-26 07:11 UTC, knopers8 approved these changes
Great, thank you!

2023-05-26 07:12 UTC, merged