Adding Laser Aging Task with adjustable amplitude cut
AliceO2Group/QualityControl pull request #1990
Opened 2023-09-16 11:16 UTC by sandor-lokos

Aging monitoring task is implemented with an additional configurable parameter that perform cut on the amplitude.

2023-09-18 08:24 UTC, andreasmolander commented on Modules/FIT/FT0/src/LaserAgingFT0Task.cxx
> +  }
I think some change is needed here, either the amp cut is channel wise or it is not?

2023-09-18 08:26 UTC, andreasmolander approved these changes

2023-09-19 06:48 UTC, knopers8 requested changes
I have only some suggestions regarding adherence to the O2 coding guidelines and removing the leftovers from the class skeleton.

2023-09-19 06:48 UTC, knopers8 commented on Modules/FIT/FT0/src/LaserAgingFT0Task.cxx
> +/// \author My Name
```suggestion
/// \author Sandor Lokos
```

2023-09-19 06:48 UTC, knopers8 commented on Modules/FIT/FT0/src/LaserAgingFT0Task.cxx
> +  ILOG(Info, Support) << "Info" << ENDM;                        // QcInfoLogger is used. FairMQ logs will go to there as well.
```suggestion
  ILOG(Debug, Devel) << "initialize LaserAgingFT0Task" << ENDM;
```
from all of this, you probably need just that

2023-09-19 06:48 UTC, knopers8 commented on Modules/FIT/FT0/src/LaserAgingFT0Task.cxx
> +    entry.second->Reset();
```suggestion
  for (auto& entry : mMapHistAmpVsBCADC0) {
    entry.second->Reset();
  }
  for (auto& entry : mMapHistAmpVsBCADC1) {
    entry.second->Reset();
  }
```
https://rawgit.com/AliceO2Group/CodingGuidelines/master/naming_formatting.html?showone=Braces#Braces

2023-09-19 06:48 UTC, knopers8 commented on Modules/FIT/FT0/src/LaserAgingFT0Task.cxx
> +  // THUS FUNCTION BODY IS AN EXAMPLE. PLEASE REMOVE EVERYTHING YOU DO NOT NEED.
```suggestion
```

2023-09-19 06:48 UTC, knopers8 commented on Modules/FIT/FT0/src/LaserAgingFT0Task.cxx
> +  // THUS FUNCTION BODY IS AN EXAMPLE. PLEASE REMOVE EVERYTHING YOU DO NOT NEED.
```suggestion
```
it's not an example anymore ;)

2023-09-19 06:48 UTC, knopers8 commented on Modules/FIT/FT0/src/LaserAgingFT0Task.cxx
> +        mHistAmp2ADC0->Fill(static_cast<Double_t>(chData.ChId), static_cast<Double_t>(chData.QTCAmpl));
```suggestion
      if (chData.getFlag(o2::ft0::ChannelData::kNumberADC)) {
        mHistAmp2ADC1->Fill(static_cast<Double_t>(chData.ChId), static_cast<Double_t>(chData.QTCAmpl));
      }
      else {
        mHistAmp2ADC0->Fill(static_cast<Double_t>(chData.ChId), static_cast<Double_t>(chData.QTCAmpl));
      }
```

2023-09-19 06:48 UTC, knopers8 commented on Modules/FIT/FT0/src/LaserAgingFT0Task.cxx
> +
```suggestion
```

2023-09-19 06:48 UTC, knopers8 commented on Modules/FIT/FT0/src/TH1ReductorLaser.cxx
> +    std::cerr << histo << std::endl;
```suggestion
```
Please avoid using directly stderr, this will be anyway redirected to infologger, but as warnings.

2023-09-19 06:48 UTC, knopers8 commented on Modules/FIT/FT0/src/TH1ReductorLaser.cxx
> +// ILOG(Warning)<<histo->GetName()<<" entries: "<< bc_projection->GetEntries()<<" channel: "<<channel<<" ibc: "<<ibc<<" ibc_max: "<<ibc_max<<ENDM;
```suggestion
```

2023-09-19 06:48 UTC, knopers8 commented on Modules/FIT/FT0/src/TH1ReductorLaser.cxx
> +          stdv = 0.5;
```suggestion
        if (stdv < 0.5) {
          stdv = 0.5;
        }
```

2023-09-20 07:48 UTC, andreasmolander commented
No need to merge yet. We noticed more changes are needed, I will take care of these, including Piotr's points.

2024-02-29 13:04 UTC, andreasmolander commented
Closing as the functionality was included in: https://github.com/AliceO2Group/QualityControl/pull/2130

2024-02-29 13:04 UTC, closed without merging