TRD: Grab CCDB Chamber Status for plots
AliceO2Group/QualityControl pull request #2075
Opened 2023-12-15 14:32 UTC by leo-barreto

## Main Goal
To add the information of Chamber Status, saved in CCDB, to the following QC plots: `trackletsperHC2D`, `TrackletsPerMCM_Layer[0..5]` and `DigitsPerLayer_[0..5]`.

Half chamber status is showed as a black box with a X in it, whenever chamber status is considered **BAD**, i.e. different from CONFIGURED "3" and EMPTY/no data from DCS "0". 

See plots as examples (for simulated data).
![trackletsperHC2D](https://github.com/AliceO2Group/QualityControl/assets/20586938/c7ce5ccc-5313-4f6b-8ef2-de5ed0fe0b1e)

![TrackletsPerMCM_Layer0](https://github.com/AliceO2Group/QualityControl/assets/20586938/84c9bd30-b9dd-4c31-bf36-ba4a8057090a)

![DigitsPerLayer_0](https://github.com/AliceO2Group/QualityControl/assets/20586938/ea92985b-f274-4321-abc6-4fcfcd2aec06)

Also, clean up and organization of TrackletsTask and DigitsTask.

---
Relevant JIRA: [TRD 109](https://alice.its.cern.ch/jira/browse/TRD-109)
Relevant O2 PR: [TRD: Implementation of DCS Chamber Status processing and DPs update](https://github.com/AliceO2Group/AliceO2/pull/12319)

2023-12-15 15:52 UTC, martenole commented
Thanks @leo-barreto ! Did not go through it in detail yet. But could you please also cross out the chambers which did not send any data to the DCS processor? Possibly in another color (gray?), but if that's not easily possible then black also works.
And thanks for the cleanup! To improve the readability and maintainability even more, could you please create a new class, called e.g. TRDHelpers and move all the generic functions which are used both in the tracklets and digits task in there? That reduced the size of the code and if anything is changed in the future one could otherwise easily forget to update both tasks..

2023-12-21 13:11 UTC, martenole requested changes
Thanks Leonardo, I think this looks already quite good. But while we're doing some cleanup I think it would be good to make the methods in `TRDHelpers` a bit clearer. Sometimes the names are not super descriptive. And if we cannot find a better name we should at least add some comments describing what the method is doing. I know these are all "inherited problems".. But it would be great if we could improve the readability of our code, also for future developers

2023-12-21 13:11 UTC, martenole commented on Modules/TRD/include/TRD/TRDHelpers.h
> +  void drawChamberStatusOn2D(std::shared_ptr<TH2F> hist, const std::array<int, o2::trd::constants::MAXCHAMBER>* ptrChamber);
Can we not use only this method and get rid off `drawChamberStatusOnLayers`?

2023-12-22 01:39 UTC, leo-barreto commented on Modules/TRD/src/TRDHelpers.cxx
> +            std::cout << "Leonardo hcstat " << hcstat << std::endl;
My bad! :sweat_smile:

2023-12-22 09:39 UTC, martenole approved these changes
Looks good now! Did you test your latest changes and could you confirm that the DigitsTask and TrackletsTask are producing the objects as you expect them @leo-barreto ? From my side this would then be ready for merging

2023-12-22 09:49 UTC, martenole commented
Actually, I see only now that there are conflicts in CMakeLists.txt. Could you please resolve them? In the current maser some classes have been removed.

2023-12-22 15:44 UTC, leo-barreto commented
@martenole I did a quick "hand-crafted" chamber status configuration for testing (also uploaded to [ccdb-test](http://ccdb-test.cern.ch:8080/browse/TRD/Calib/DCSDPsFedChamberStatus)). 

It should show, for `i` being the chamber ID:
  - Empty (grey X): `i % 30 == 6`
  - Error (red X): `i` being 42, 121, 420
  - Other masked (black X): `i` between 162 and 179 
  - Everything else: no mask
  
 Current results are: 
![trackletsperHC2D_test](https://github.com/AliceO2Group/QualityControl/assets/20586938/cbb197bc-ff06-4186-a674-549916b90629)
![TrackletsPerMCM_Layer0_test](https://github.com/AliceO2Group/QualityControl/assets/20586938/dab91c6f-1206-44df-8765-481eaf12ec94)
![DigitsPerLayer_0_test](https://github.com/AliceO2Group/QualityControl/assets/20586938/a71e1a0c-161c-4924-a72b-f099edaf6e85)

I had a quick glance at the other plots, and they seem unchanged.

**Thus everything seems okay on my part.**

2023-12-22 19:45 UTC, leo-barreto commented
There is an error caught on the automatic build: 

> reco_NOGPU.log-[80011:qc-task-TRD-Tracklets]: [19:10:30][WARN] Did not find object under expected name ccdb_object
> reco_NOGPU.log:[80011:qc-task-TRD-Tracklets]: [19:10:30][ERROR] Exception caught: Couldn't retrieve object corresponding to array<int,540> from TFile

(same thing for qc-task-TRD-Digits)

Maybe this could be fixed with changing the [TRDQC.json](https://github.com/AliceO2Group/QualityControl/blob/64fa7f18968589110b8f2b2b9f34458ba0be86fc/Modules/TRD/TRDQC.json#L60)? "querry" should be changed to the new CCDB path (TRD/Calib/DCSDPsChamberStatus).

@martenole let me know what you think. I'll wait for confirmation before commiting any change to the json file (I don't have it latest version in my branch).

2024-01-15 12:26 UTC, martenole approved these changes
All checks are passing now. From my side this can be merged

2024-01-16 09:19 UTC, leo-barreto commented
Everything also good from my side for merge

2024-01-22 12:00 UTC, martenole commented
Hi @Barthelemy or @knopers8 could this be merged?

2024-01-22 12:03 UTC, Barthelemy approved these changes

2024-01-22 12:04 UTC, merged