CTP: Trending
AliceO2Group/QualityControl pull request #2101
Opened 2024-01-23 17:14 UTC by lhusova

Trending of input and class rates

2024-01-24 09:49 UTC, Barthelemy reviewed
Hi, 

Thank you !

I made a first quick review. Please see my comments. @knopers8 do you want to have a look too or not ? 

One thing that I would like to discuss is the number of plots. 100 more plots is non-negligible. Could some be grouped ? Could a higher dimension plot be used ? How many more are expected to come in the future ? 

It is crucial for the QCDB to limit the amount of objects that are updated at fast pace such as this one and that are then kept long term.

2024-01-24 09:49 UTC, Barthelemy commented on Modules/CTP/CMakeLists.txt
> +get_property(dirs
could you remove this if it is only there to debug ?

2024-01-24 09:49 UTC, Barthelemy commented on Modules/CTP/src/CTPTrendingTask.cxx
> +        inputIndex++;
It is recommended to put braces even when there is a single line

2024-01-24 09:49 UTC, Barthelemy commented on Modules/CTP/src/CTPTrendingTask.cxx
> +          histo->SetTitle(ctpInputs[inputIndex].name.c_str());
It is recommended to put braces even when there is a single line

2024-01-24 09:49 UTC, Barthelemy commented on Modules/CTP/src/CTPTrendingTask.cxx
> +    if (index < numberOfInputs && index != trendedInputIndex[inputIndex] - 1) {
A bit of documentation on what is being done here would be nice. In particular given that there are two conditions leading in the end to the same duplicated code.

2024-01-24 09:49 UTC, Barthelemy commented on Modules/CTP/include/CTP/CTPTrendingTask.h
> +  struct MetaData {
Why do you need this struct ? you could directly store the activity or just the run number if needed.

2024-01-24 14:09 UTC, knopers8 requested changes

2024-01-24 14:09 UTC, knopers8 commented on Modules/CTP/src/CTPTrendingTask.cxx
> +  if (!foundInputs) {
I am wondering if you really should add another row in the tree if you manage to retrieve only some objects from the QCDB. What may happen is that your new row will consists of partially obsolete values, which might be misleading. Up to you to decide if this is what you want.

If not, you could invert the logic and have `bool inputMissing = false;` which is set to true when one of the `retrieveMO` calls fails, then you can skip `mTrend->Fill()`.

2024-01-24 14:09 UTC, knopers8 commented on Modules/CTP/src/CTPTrendingTask.cxx
> +      ILOG(Info, Support) << "Input " << input.getIndex() << " should not exist!!" << ENDM;
Should it be a warning perhaps?

2024-01-24 14:09 UTC, knopers8 commented on Modules/CTP/src/CTPTrendingTask.cxx
> +      ILOG(Info, Support) << plot.varexp << " " << plot.selection << " " << plot.option << ENDM;
This looks like a debug or developer log.

2024-01-24 14:09 UTC, knopers8 commented on Modules/CTP/src/CTPTrendingTask.cxx
> +  // Preparing data structure of TTree
Please delete any existing pointers in `mPlots` and clear it to account for the correct START -> STOP -> START sequence

2024-02-12 14:01 UTC, knopers8 commented on Modules/CTP/include/CTP/TH1ctpReductor.h
> +namespace o2::quality_control::postprocessing
Since this Reductor is CTP-specific, I would keep it within the `o2::quality_control_modules::ctp` namespace.

2024-02-12 14:06 UTC, knopers8 commented on Modules/CTP/include/CTP/TH1ctpReductor.h
> +class TH1ctpReductor : public quality_control::postprocessing::Reductor
```suggestion
class TH1ctpReductor : public quality_control::postprocessing::ReductorTObject
```
There was a change in the framework while you were working on your PR. Essentially, you have to inherit now `ReductorTObject`. You may have a look how I adapted the tasks which were already in the codebase: https://github.com/AliceO2Group/QualityControl/pull/2110/files

2024-02-16 15:26 UTC, merged