TOF: setting url to the ccdb
AliceO2Group/QualityControl pull request #2173
Opened 2024-03-11 15:43 UTC by sofiatomassini

the url to get the reference map in the ccdb is now set correctly. 
@Barthelemy  could you please merge this PR? Thank you!

2024-03-11 15:51 UTC, njacazio commented
@Barthelemy we were wondering if this is how we should set up the CCDB call to customize the URL. Thanks and cheers,
N.

2024-03-12 14:22 UTC, Barthelemy requested changes
Hi, 

I understand that you want to retrieve something from the CCDB ? 

There are several ways of doing it. You should not set the url yourself. The URL is set in the config file. 

The documentation is here: 
https://github.com/AliceO2Group/QualityControl/blob/master/doc/Advanced.md#accessing-objects-in-ccdb

The recommended way is to use Lifetime::Condition DPL input. There are many examples in the Modules. 

We don't recommend but don't forbid either to use `retrieveConditionAny` which would let you retrieve the CCDB data as well. It is ready to use and does not require any extra configuration.

2024-03-12 14:52 UTC, knopers8 commented
PostProcessingTasks do not take DPL inputs, so in this case `retrieveConditionAny` should be used.

2024-03-13 12:17 UTC, sofiatomassini commented
Indeed, however the `PostProcessingInterface.h` does not depend on `UserCodeInterface.h` where the `retrieveConditionAny` is defined. For instance in `Modules/CPV/src/PhysicsTask.cxx` it can be used  because the `TaskInterface.h` is dependent on `UserCodeInterface.h`. Did I understand correctly how It works? Thank you !

2024-03-13 12:40 UTC, knopers8 commented
PostProcessingInterface does inherit UserCodeInterface since two months: https://github.com/AliceO2Group/QualityControl/blob/07bdae6d68188960dd14c5be555d149c4bd17ee9/Framework/include/QualityControl/PostProcessingInterface.h#L37
Perhaps you have to rebase with the master branch?

2024-03-13 13:15 UTC, Barthelemy commented
I am updating the documentation accordingly

2024-03-18 12:38 UTC, njacazio requested changes

2024-03-18 12:38 UTC, njacazio commented on Modules/TOF/include/Base/MessagePad.h
> -  float mPadLowY = 0.5;                 /// Position of the message PAD in low y
don't change these

2024-03-18 12:38 UTC, njacazio commented on Modules/TOF/include/Base/MessagePad.h
> -    mMessagePad->SetName(Form("%s_msg", histogram->GetName()));
this is ok

2024-03-18 12:38 UTC, njacazio commented on Modules/TOF/include/Base/MessagePad.h
> +  const std::string mName = "msg";      /// Name of the message pad, can be used to identify the pad if multiple are used
this is ok

2024-03-18 12:38 UTC, njacazio commented on Modules/TOF/src/PostProcessHitMap.cxx
> -  const auto mo = mDatabase->retrieveMO(mCCDBPath, mCCDBPathObject, t.timestamp, t.activity);
Don't change this

2024-03-18 12:38 UTC, njacazio commented on Modules/TOF/src/PostProcessHitMap.cxx
> +  // const auto* refmap = o2::ccdb::BasicCCDBManager::instance().getForTimeStamp<o2::tof::TOFFEElightInfo>(mRefMapCcdbPath, mRefMapTimestamp);
This can be cleaned

2024-03-18 12:38 UTC, njacazio commented on Modules/TOF/src/PostProcessHitMap.cxx
> +#include "CCDB/CcdbApi.h"
These new includes are not needed then, right?

2024-03-18 12:38 UTC, njacazio commented on Modules/TOF/src/PostProcessHitMap.cxx
> -  mCCDBPathObject = config.get<std::string>(baseJsonPath + "CCDBPathObject", "HitMapNoiseFiltered");
Keep both

2024-03-18 12:38 UTC, njacazio commented on Modules/TOF/src/PostProcessHitMap.cxx
> +  o2::ccdb::BasicCCDBManager::instance().setURL(mCCDBUrl);
This might not be needed

2024-03-18 16:06 UTC, njacazio approved these changes

2024-03-19 13:10 UTC, njacazio commented
Ok @Barthelemy it should be good to merge

2024-03-19 14:07 UTC, Barthelemy commented
why do you need `mCCDBUrl` ?

2024-03-19 14:11 UTC, njacazio commented
Indeed it was not needed

2024-03-19 14:14 UTC, Barthelemy approved these changes

2024-03-19 14:18 UTC, njacazio approved these changes

2024-03-19 22:40 UTC, merged