Separation power for Pions and Electrons
AliceO2Group/QualityControl pull request #2225
Opened 2024-04-05 08:49 UTC by HorstMa

This PR adds the separation power that can be trended for pions and electrons at the MIP point.
This is related to the O2 PR https://github.com/AliceO2Group/AliceO2/pull/12988

2024-04-05 10:04 UTC, wiechula requested changes

2024-04-05 10:04 UTC, wiechula commented on Modules/TPC/src/PID.cxx
> +  getObjectsManager()->startPublishing(cSeparationPower);
```suggestion
  mSeparationPower = mQCPID.getSeparationPower();
  getObjectsManager()->startPublishing(mSeparationPower);
```

2024-04-05 10:04 UTC, wiechula commented on Modules/TPC/src/PID.cxx
> +
Why is this inside the loop? The same fit function is used. So either:
- put it on the stack, or
- move it outside the and make it a `unique_ptr`.

2024-04-05 10:04 UTC, wiechula commented on Modules/TPC/src/PID.cxx
> +  pSeparationPower->AddText(fmt::format("Mean El: {:.3}", mTrendingParameters[2]).c_str());
Add sigmas.

2024-05-28 07:20 UTC, HorstMa commented
@knopers8 They are related to the O2 PR which has not yet been merged https://github.com/AliceO2Group/AliceO2/pull/12988

2024-06-06 16:45 UTC, wiechula approved these changes

2024-06-07 00:38 UTC, merged