[EMCAL-792] Added checker for raw error check (all types, last minute)
AliceO2Group/QualityControl pull request #2279
Opened 2024-05-06 10:45 UTC by anabananana98

Added checker for raw error check (all types, last minute) which uses a moving average to determine if error rates are within threshold values

2024-05-07 09:24 UTC, mfasDa requested changes
Still a few issues to fix

2024-05-07 09:24 UTC, mfasDa commented on Modules/EMCAL/src/RawErrorCheckAll.cxx
> +using namespace std;
`Using` of whole namespaces must never be applied except the one declared in the header. In particular don't apply `using namespace std`, or of any member of the standard namespace.

2024-05-07 09:24 UTC, mfasDa commented on Modules/EMCAL/src/RawErrorCheckAll.cxx
> +            ILOG(Error, Support) << fmt::format("Value {} not a double", nBadThreshold->second.data()) << ENDM;
For c++ streams like `ILOG` you don't need any formatting library, as this is handled by the iostream library. In any case, with c++20's std::format the format library anyhow kind of becomes obsolete.

2024-05-07 09:24 UTC, mfasDa commented on Modules/EMCAL/src/RawErrorCheckAll.cxx
> +                double numPoints = trendgraph->GetN();
You need int here. Better use `auto` for capturing return values.

2024-05-07 09:24 UTC, mfasDa commented on Modules/EMCAL/src/RawErrorCheckAll.cxx
> +            auto* c = dynamic_cast<TCanvas*>(mo->getObject());
Meaningful names

2024-05-07 09:24 UTC, mfasDa commented on Modules/EMCAL/src/RawErrorCheckAll.cxx
> +                double sum;
`sum` uninitialized, leads to random behaviour

2024-05-22 09:55 UTC, mfasDa requested changes
Almost ready - please fix the two leftover cases and then I merge it.

2024-05-22 09:55 UTC, mfasDa commented on Modules/EMCAL/src/RawErrorCheckAll.cxx
> +      ILOG(Error, Support) << ("Value {} not a double", nBadThreshold->second.data()) << ENDM;
Doesn't work - see other PR

2024-05-22 09:55 UTC, mfasDa commented on Modules/EMCAL/src/RawErrorCheckAll.cxx
> +      ILOG(Error, Support) << ("Value {} not an int", nPeriodMovAvg->second.data()) << ENDM;
Same here

2024-05-23 08:18 UTC, mfasDa approved these changes
Looks good now.

2024-05-23 09:24 UTC, knopers8 commented
please resolve the merge conflict.

2024-05-29 06:40 UTC, merged