[EMCAL-767] Added the TRU gridlines to the TRU Mask Position MO
AliceO2Group/QualityControl pull request #2368
Opened 2024-07-04 20:33 UTC by sweyh99

2024-07-05 06:27 UTC, Barthelemy approved these changes

2024-07-05 12:06 UTC, mfasDa requested changes
I think you could modify the code in a way that no extra canvas is needed. It is done in a same way for the supermodule grid in the acceptance plots by the CellCheck. In order to do so you make use of 
```c++
histo->GetListOfFunctions()->Add(line);
```
for each line to add. In that case you pass a 2D histogram to the function.

Ideally, I would like to move the function -  as well as the code for the supermodule grid - to a helper class in order to avoid code duplication. We need this in more places, therefore it would be helpful to generalise.

Last, with such a restructuring I would suggest the following sequence:
- Supermodule grid
- TRU grid (1/3rd supermodue)
- FastOR grid
in separate functions. Like this we can combine as needed.

2024-08-06 07:59 UTC, mfasDa requested changes
Only a minor change needed

2024-08-06 07:59 UTC, mfasDa commented on Modules/EMCAL/include/EMCAL/CalibMonitoringTask.h
> +  TCanvas* mTRUMaskPositionCanvas = nullptr;          ///< The FastOR Mask Position in Eta, Phi Canvas
There is still an unused TCanvas in

2024-08-06 15:58 UTC, mfasDa approved these changes
Now ready to merge

2024-08-06 18:28 UTC, merged