Update utility for timestamp extraction to optimize it
AliceO2Group/QualityControl pull request #2432
Opened 2024-09-23 17:21 UTC by lauraser

+ switches for IDC task what to plot

2024-09-24 07:50 UTC, knopers8 approved these changes

2024-09-24 08:22 UTC, wiechula requested changes

2024-09-25 11:17 UTC, lauraser commented
@wiechula I implemented all your suggestions. Regarding the call .list() for last two weeks, I also additionally added checks if at least one object version was found. If not, then files are not retreived (otherwise there is seg fault). Please, let me know if you want any additional changes

2024-09-26 06:33 UTC, Barthelemy commented
@wiechula @lauraser We need to release QC this morning and this is the last release before the freeze. We can do adhoc patches afterward yet we should aim at merging this PR this morning. 
Could you approve and merge ?
thank you

2024-09-26 08:17 UTC, wiechula approved these changes

2024-09-26 08:17 UTC, merged

2024-09-26 08:18 UTC, wiechula commented
@Barthelemy , done.