Make Policies a separate class (QC-342)
AliceO2Group/QualityControl pull request #483
Opened 2020-09-16 13:53 UTC by Barthelemy

Policies and revisions were spread over `Check` and `CheckRunner` making it difficult to comprehend and to reuse (e.g. in the future aggregators). 

This PR proposes an extraction of these concepts in a separate class called `PolicyManager`. The `Check` class is unaware of the notion of revisions. It still holds its own configuration and thus the policy definition. As a consequence the PolicyManager is indirectly influenced by the way the `Check` class overwrites the policy name in certain cases. This is something we should reconsider in the future. 

I have kept the use of lambdas to implement the actual logic of the different types of policies. Again, this is something we might want to reconsider in the future. The fact that there is a `policyHelper` parameter necessary to hold a state of one of the type of policies is a sign that we might want to move away from simple lambdas. A more traditional OO approach with a common interface and a set of classes implementing the actual policy function could be a solution. 

All in all it is not my dream refactoring but it achieves the extraction of the code related to policies and revisions from `Check` and `CheckRunner` and improves the separation of concerns.

2020-09-18 12:47 UTC, Barthelemy commented
No idea what is going on with the CI.

2020-09-21 07:29 UTC, Barthelemy commented
@ktf o2-dataflow  is still failing

2020-09-21 10:39 UTC, ktf commented
restarted

2020-09-21 13:13 UTC, knopers8 requested changes
Thanks, this looks much better already!

I would propose to change `Policy` to `UpdatePolicy`, since the former is too general IMO. Likewise, `PolicyManager` to `UpdatePolicyManager`

Could you also change the PR name to something more accurate? After all, Policies didn't become classes yet.

In later refactoring, I also thought about making UpdatePolicies return object names which should be checked. That should clean up the `Check::check()` method, which is a monster now. This probably is for later though.

2020-09-21 13:13 UTC, knopers8 commented on Framework/test/testPolicyManager.cxx
> +using namespace o2::utilities;
Not needed

2020-09-21 13:31 UTC, Barthelemy commented
Thanks for the great review. I'll update the PR accordingly. 

@MichaelLettrich It seems that the mac builder is broken again.

2020-09-21 13:53 UTC, knopers8 commented
I have tried manually if the OneEachSeparately policy still works - it seems it does.

2020-09-21 14:04 UTC, Barthelemy commented on Framework/src/PolicyManager.cxx
> +
I left it in order not to touch the logic that pre-existed between the policies and the Check class. The Check updates the policy depending for example on the "all" parameter and sets it to this _OnGlobalAny. I would leave it for now and wait for the next round of refactoring.

2020-09-21 14:11 UTC, knopers8 commented on Framework/src/PolicyManager.cxx
> +
ok

2020-09-21 14:57 UTC, knopers8 approved these changes
Thanks for the fixes, please just fix the formatting in CMakeLists after CLion (i guess) destroyed it.

2020-09-21 14:57 UTC, knopers8 commented on Framework/CMakeLists.txt
> +  src/UpdatePolicyManager.cxx)
Please fix the indentation

2020-09-21 14:57 UTC, knopers8 commented on Framework/CMakeLists.txt
> +  include/QualityControl/UpdatePolicyManager.h
Please fix the indentation

2020-09-21 14:57 UTC, knopers8 commented on Framework/src/TaskRunner.cxx
> +  ConfigurationInterface* config = policiesFilePath.empty() ? mConfigFile.get() : ConfigurationFactory::getConfiguration(policiesFilePath).get(); // todo make sure that it is ok to use the internal p
nice catch, it looks dangerous indeed

2020-09-22 08:36 UTC, merged