[WIP] [QC-491] PP Task to transform Quality Objects into TRFCollections
AliceO2Group/QualityControl pull request #623
Opened 2021-02-26 14:34 UTC by knopers8

Needs https://github.com/AliceO2Group/AliceO2/pull/5554

2021-03-11 14:40 UTC, Barthelemy requested changes
Very few comments, just cosmetics. Very good.

2021-03-11 14:40 UTC, Barthelemy commented on Modules/Common/include/Common/TRFCollectionTask.h
> +  //  o2::analysis::TimeRangeFlagCollection mTRFCollection;
remove commented code.

2021-03-11 14:40 UTC, Barthelemy commented on Modules/Common/include/Common/TRFCollectionTask.h
> +#ifndef QUALITYCONTROL_SKELETONPOSTPROCESSING_H
name incorrect

2021-03-11 15:05 UTC, knopers8 commented on Framework/src/Quality.cxx
> +  namespace o2::quality_control::core
it is the ClassImp above which breaks the formatting by clang-format. But we can actually remove it, can't we?

2021-03-11 18:54 UTC, Barthelemy commented on Framework/src/Quality.cxx
> +  namespace o2::quality_control::core
yes we can

2021-03-11 18:54 UTC, Barthelemy commented on Framework/src/Quality.cxx
> +  namespace o2::quality_control::core
unimportant though, I merge

2021-03-11 18:55 UTC, Barthelemy approved these changes

2021-03-11 18:55 UTC, merged

2021-03-12 07:15 UTC, knopers8 commented on Framework/src/Quality.cxx
> +  namespace o2::quality_control::core
I didn't push the other changes yet anyway, I will make another PR