For pilot2 d
AliceO2Group/QualityControl pull request #859
Opened 2021-10-04 17:50 UTC by lauraser

The following check takes a canvas as input, loops over all figures containing IROCs and OROCs in the canvas and checks for empty pads. 
Besides storing the main quality object, it has private member to store qualities for every histogram which are later used in beautify to show specific quality for every histogram instead of the entire canvas.
@wiechula Stefan suggested the limits for medium quality 30% of pads empty and for bad 60% of pads empty. Do you think this is reasonable?

2021-10-05 07:20 UTC, Barthelemy commented
I let @wiechula  review this PR.

2021-10-05 08:23 UTC, wiechula requested changes
@lauraser , thanks for the code.
I have many small comments to improve code readability mainly. For the future, in general, please always
* use `const` whenever possible
* always use readability braces

2021-10-05 08:23 UTC, wiechula commented on Modules/TPC/src/PadCalibrationCheck2D.cxx
> +        return Quality::Null;
add readability braces and simplify expression (assuming it cannot be both, IROC and OROC). Also, the IROC / OROC distinction is only used to get the total number of pads.

```suggestion
      int totalPads = 0;
      if (titleh.find("IROC") != std::string::npos) {
        totalPads = 5280;
      } else if (titleh.find("OROC") != std::string::npos) {
        totalPads = 9280;
      } else {
        return Quality::Null;
      }
```

2021-10-05 08:23 UTC, wiechula commented on Modules/TPC/src/PadCalibrationCheck2D.cxx
> +      auto histName = fmt::format("h_Pedestals_ROC_{:02d}", tpads - 1);
```suggestion
      const auto padName = fmt::format("c_ROCs_Pedestal_2D_{:d}", tpads);
      const auto histName = fmt::format("h_Pedestals_ROC_{:02d}", tpads - 1);
```

2021-10-05 08:23 UTC, wiechula commented on Modules/TPC/src/PadCalibrationCheck2D.cxx
> +    auto* canv = dynamic_cast<TCanvas*>(mo->getObject());
dynamic cast only makes sense if you want the verify the object type. So I guess you should either change this to `static_cast` of c-style cast `(TCanvas*)` or add
```c++
if (!canv) {
  return Quality::Null;
}

2021-10-05 08:23 UTC, wiechula commented on Modules/TPC/src/PadCalibrationCheck2D.cxx
> +      std::string titleh = h->GetTitle();
```suggestion
      const std::string titleh = h->GetTitle();
```

2021-10-05 08:23 UTC, wiechula commented on Modules/TPC/src/PadCalibrationCheck2D.cxx
> +        totalPads = 9280;
Not needed, see above.
```suggestion
```

2021-10-05 08:23 UTC, wiechula commented on Modules/TPC/src/PadCalibrationCheck2D.cxx
> +      int NY = h->GetNbinsY();
```suggestion
      const int NX = h->GetNbinsX();
      const int NY = h->GetNbinsY();
```

2021-10-05 08:23 UTC, wiechula commented on Modules/TPC/src/PadCalibrationCheck2D.cxx
> +      float badLimit = 0.4;
Shouldn't this be configurable from the json file?
```suggestion
      const float mediumLimit = 0.7;
      const float badLimit = 0.4;
```

2021-10-05 08:23 UTC, wiechula commented on Modules/TPC/src/PadCalibrationCheck2D.cxx
> +          result = Quality::Medium;
```suggestion
        if (result == Quality::Good) {
          result = Quality::Medium;
        }
```

2021-10-05 08:23 UTC, wiechula commented on Modules/TPC/src/PadCalibrationCheck2D.cxx
> +      bool oroc = false;
Not needed, see below.
```suggestion
```

2021-10-05 08:23 UTC, wiechula commented on Modules/TPC/src/PadCalibrationCheck2D.cxx
> +  auto* canv = dynamic_cast<TCanvas*>(mo->getObject());
See comment above.

2021-10-05 08:23 UTC, wiechula commented on Modules/TPC/src/PadCalibrationCheck2D.cxx
> +    auto histName = fmt::format("h_Pedestals_ROC_{:02d}", tpads - 1);
```suggestion
    const auto padName = fmt::format("c_ROCs_Pedestal_2D_{:d}", tpads);
    const auto histName = fmt::format("h_Pedestals_ROC_{:02d}", tpads - 1);
```

2021-10-05 08:23 UTC, wiechula commented on Modules/TPC/src/PadCalibrationCheck2D.cxx
> +    std::string titleh = h->GetTitle();
```suggestion
    const std::string titleh = h->GetTitle();
```

2021-10-05 08:23 UTC, wiechula commented on Modules/TPC/src/PadCalibrationCheck2D.cxx
> +      int index = std::distance(badSectorsName.begin(), it);
```suggestion
      const int index = std::distance(badSectorsName.begin(), it);
```

2021-10-05 08:23 UTC, wiechula commented on Modules/TPC/src/PadCalibrationCheck2D.cxx
> +    std::vector<std::string>::iterator it = std::find(badSectorsName.begin(), badSectorsName.end(), titleh);
```suggestion
    auto it = std::find(badSectorsName.begin(), badSectorsName.end(), titleh);
```

2021-10-05 08:23 UTC, wiechula commented on Modules/TPC/src/PadCalibrationCheck2D.cxx
> +    if (it != badSectorsName.end()) {
Change logic to make clear that the reader does not have to continue reading the code:
```suggestion
    if (it == badSectorsName.end()) {
      continue
    }
```

2021-10-05 20:34 UTC, wiechula approved these changes

2021-10-05 22:04 UTC, wiechula approved these changes

2021-10-06 07:19 UTC, wiechula commented
@Barthelemy , seem it is not merged.

2021-10-06 09:45 UTC, merged