The check for trends, comparing new point to average
AliceO2Group/QualityControl pull request #864
Opened 2021-10-05 13:57 UTC by lauraser

The following check is performed on all trends currently available in the QC. The medium quality applied for >3sigma deviations, bad quality for >6sigma deviations.

2021-10-05 18:29 UTC, wiechula requested changes

2021-10-05 18:29 UTC, wiechula commented on Modules/TPC/src/CheckOfTrendings.cxx
> +using namespace std;
Please don't use this and `std::` where needed. You do it in most places anyhow.
```suggestion
```

2021-10-05 18:29 UTC, wiechula commented on Modules/TPC/src/CheckOfTrendings.cxx
> +  const double mean = sum / v.size();
is check for division by zero needed?

2021-10-05 18:58 UTC, wiechula approved these changes

2021-10-06 06:52 UTC, wiechula commented
I think the macos failures are again unrelated

2021-10-06 07:19 UTC, wiechula commented
@Barthelemy , can this be merged?

2021-10-06 09:47 UTC, Barthelemy commented
yes. just trying to fix the mac build at the same time. I fixed a conflict here.

2021-10-06 09:50 UTC, wiechula commented
@Barthelemy , thanks! I didn't spot this.

2021-10-06 11:57 UTC, merged